apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyuytytt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyuytytt
  template:
    metadata:
      labels:
        app: hyuytytt
    spec:
      containers:
      - image: okteto.dev/hyuytytt:latest
        name: hyuytytt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2c8b53ed-a765-421a-bd52-74c8ba963744"
        - name: Vless_Path
          value: "/vlrtgffggf"
        - name: Vmess_UUID
          value: "2c8b53ed-a765-421a-bd52-74c8ba963744"
        - name: Vmess_Path
          value: "/vmrfdfgfdtg6tf"
        - name: Share_Path
          value: "/v2link"
